name: Staging Deploy
on:
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  staging-main:
    uses: ./.github/workflows/shared.yml
    with:
      environment: staging
      working_directory: ./env/staging
      auto_apply: true
    secrets: inherit
  
  staging-test-bucket:
    uses: ./.github/workflows/shared.yml
    with:
      environment: staging
      working_directory: ./env/staging/test-bucket
      auto_apply: true
    secrets: inherit

  staging-secrets:
    uses: ./.github/workflows/shared.yml
    with:
      environment: staging
      working_directory: ./env/staging/secrets
      auto_apply: true
    secrets: inherit

